# Generated by Django 3.0.3 on 2020-02-13 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_user'),
        ('users', '0002_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='users', to='tasks.Task'),
        ),
        migrations.CreateModel(
            name='TaskReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
                ('task_performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='users.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tasks_on_review',
            field=models.ManyToManyField(blank=True, through='users.TaskReview', to='tasks.Task'),
        ),
    ]
