# Generated by Django 3.0.3 on 2020-02-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_user'),
        ('users', '0003_auto_20200214_0106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskreview',
            unique_together={('user', 'task', 'task_performer')},
        ),
    ]
